### PR TITLE
State, base filters added to prs

### PR DESCRIPTION
**Pull request by sonali-amura**
Screenshot from 2020-04-18 11-00-38

---
This change is [Reviewable](https://reviewable.io/reviews/amuratech/digiflash/10)

### CODE REVIEW

**Comment by sonali-amura** [comment]
> > _[Reviewable](https://reviewable.io/reviews/amuratech/digiflash/10)_ status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @huzefa-amura, @pooja-amura, and @sonali-amura)
> 
> _[a discussion](https://reviewable.io/reviews/amuratech/digiflash/10#-M4rbHMM20KWAuHQt4yw:-M4rbHMM20KWAuHQt4yx:btbrth7) (no related file):_
> @sonali-amura : As per displayed in the screenshot, can you please remove the text 'No data to display' from top of the page if not required?

Done

**Comment by sonali-amura** [comment]
> -changes_done +changes_suggested
> 
> > _[Reviewable](https://reviewable.io/reviews/amuratech/digiflash/10#-:-M4yG60-DEHObQBUd-ji:bdl97my)_ status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @pooja-amura and @sonali-amura)
> 
> _[src/components/PrList.js, line 57 at r1](https://reviewable.io/reviews/amuratech/digiflash/10#-M4yEqZHDrZ3absAFvui:-M4yEqZI2iB4T63hg6jR:b-82eqtx) ([raw file](https://github.com/amuratech/digiflash/blob/590d24344f4b635f54ec2e5e13ef3ae06dd5a8df/src/components/PrList.js#L57)):_
> 
> > ```
> > <a href={
> > ```
> 
> @sonali-amura : We can't use `html` `href` tags in react. The reason is that when clicked upon the link, a brand new request is made and all the data in state and class is dumped into the memory.
> Hence we need to use `BrowserRouter` 's `Link` component for declaring any links like below
> `<BrowserRouter> <Route path="/" exact component={Dashboard} /> <Route path="/crm/pr" exact component={PrShow} /> </BrowserRouter> `

Removed this link property for now. I will add it in next pr

**Comment by huzefa-amura** [comment]
@sonali-amura : Can you please update the screenshot with the latest one after merging @pooja-amura 's PR ?

**Comment by sonali-amura** [comment]
> +changes_suggested
> 
> > _[Reviewable](https://reviewable.io/reviews/amuratech/digiflash/10#-:-M4raiqm3rPGUqMTVZFP:bckrfdr)_ status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @huzefa-amura, @pooja-amura, and @sonali-amura)
> 
> _[src/api/git.js, line 6 at r1](https://reviewable.io/reviews/amuratech/digiflash/10#-M4raVGB52Silgedcdu8:-M4raVGC2y7R4eF0uVsr:bcxnkg) ([raw file](https://github.com/amuratech/digiflash/blob/590d24344f4b635f54ec2e5e13ef3ae06dd5a8df/src/api/git.js#L6)):_
> 
> > ```
> > e2cebc6fdbb19fbef777d06912b1b30dcffb25a7'
> > ```
> 
> @sonali-amura : do not push access token as it will be revoked by github

token removed

**Pull request merged**
